src/dataset/urls.py
from django.conf.urls import url, include
import django.contrib.auth.views as auth_views
from django.views.generic import RedirectView

from . import views


app_name = 'dataset'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^sign-in/$', auth_views.login, {'template_name': 'dataset/sign-in.html'}, name='sign-in'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/', views.register, name='register'),
    url(r'^stats/', views.stats, name='stats'),
    url(r'^dataset/', views.dataset, name='dataset'),
    url(r'^downloads/([0-9]+)/', views.download_dataset, name='download_dataset'),
    url(r'^downloads/', RedirectView.as_view(pattern_name='dataset:dataset')),
]

src/proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'', include('dataset.urls')),
    url(r'^admin/', admin.site.urls),
]

src/dataset/models.py
from __future__ import unicode_literals
from random import randint

from django.db import models
from django.contrib.auth.models import User

from enchant import Dict
from enchant.tokenize import get_tokenizer


DICTIONARY = Dict('en_US')
TOKENIZER = get_tokenizer('en_US')


def default_randomness():
	return randint(0, 10000)


class MotionFile(models.Model):
	MARKER_SET_KIT = 0  # do not change values, since they are stored in the DB!
	MARKER_SET_CMU = 1
	
	class Meta:
		unique_together = ('motion_db_id', 'motion_db_file_id')
	
	motion_db_id = models.PositiveIntegerField()
	motion_db_file_id = models.PositiveIntegerField()
	filename = models.CharField(max_length=255, unique=True)
	mean_perplexity = models.FloatField(default=0.)
	is_broken_confirmed = models.BooleanField(default=False)
	is_broken_reported = models.BooleanField(default=False)
	marker_set = models.PositiveIntegerField(default=MARKER_SET_KIT)
	creation_date = models.DateTimeField(auto_now_add=True)
	update_date = models.DateTimeField(auto_now=True)
	is_hidden = models.BooleanField(default=False)

	def __str__(self):
		return self.filename


class Annotation(models.Model):
	class Meta:
		unique_together = ('user', 'motion_file')
	user = models.ForeignKey(User, on_delete=models.PROTECT)
	creation_date = models.DateTimeField(auto_now_add=True)
	motion_file = models.ForeignKey(MotionFile, on_delete=models.PROTECT)
	description = models.TextField()
	duration = models.PositiveIntegerField(default=0)
	ip_address = models.CharField(max_length=255, null=True, blank=True)
	accept_language = models.CharField(max_length=50, null=True, blank=True)
	perplexity = models.FloatField(default=0.)

	def __str__(self):
		return self.description

	def is_valid(self):
		words = [w[0] for w in TOKENIZER(self.description.lower())]
		n_words = len(words)
		if n_words == 0:
			# Return early to avoid problems with DIV by zero and such.
			return False
		
		unique_words = set(words)
		n_unique_words = len(unique_words)
		correct_unique_words = [w for w in unique_words if DICTIONARY.check(w)]
		n_correct_unique_words_words = len(correct_unique_words)
		correct_ratio = (float(n_correct_unique_words_words) / float(n_unique_words))
		n_punctuation_marks = self.description.count('.') + self.description.count('!') + self.description.count('?')

		is_valid = n_unique_words >= 3  # ... which contains at least three words
		is_valid &= correct_ratio >= 0.7  # ... of which at least 70% are spelled correctly
		is_valid &= n_punctuation_marks <= 2  # ... and the sentence only contains 2 or less punctuation marks

		return is_valid


class Dataset(models.Model):
	creation_date = models.DateTimeField(auto_now_add=True)
	filename = models.CharField(max_length=255, unique=True)
	filesize = models.PositiveIntegerField(default=0)
	nb_motions = models.PositiveIntegerField(default=0)
	nb_annotations = models.PositiveIntegerField(default=0)
	
	def __str__(self):
		return self.filename


class Download(models.Model):
	dataset = models.ForeignKey(Dataset, on_delete=models.PROTECT)
	creation_date = models.DateTimeField(auto_now_add=True)
	ip_address = models.CharField(max_length=255, null=True, blank=True)
	accept_language = models.CharField(max_length=50, null=True, blank=True)

src/dataset/views.py
import random
import time
import numpy as np

from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count, Avg
from django.contrib import messages, auth
from django.utils import timezone
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import IntegrityError, transaction
from django.conf import settings

from ipware.ip import get_ip

from .models import MotionFile, Annotation, Dataset, Download


MOTIVATIONAL_MESSAGES = ['We have saved your annotation. Thank you for helping, and keep going!',
						 'Thank you so much for helping out. You are awesome!',
						 'Today was a good day since you helped science! Keep going!',
						 'You annotate motions like there\'s no tomorrow! Thank you so much.',
						 'Who would\'ve thought that annotating motions can be this much fun, right? Thank you so much and keep going!']


LEVELS = [
	(0., 9, 'Novice', 'info'),
	(10, 49, 'Research Assistant', 'success'),
	(50, 299, 'Junior Scientist', 'warning'),
	(300, 999, 'Senior Scientist', 'danger'),
	(1000, 2999, 'Professor', 'danger'),
	(3000, 1000000, 'Donald Knuth', 'danger'),
]


def level_for_number_of_annotations(nb_annotations):
	for (lower, upper, name, klass) in LEVELS:
		if lower <= nb_annotations <= upper:
			return (lower, upper, name, klass)
	return None


def index(request):
	if not request.user.is_authenticated():
		return render(request, 'dataset/welcome.html', {})

	context = {}
	if 'motion_file_id' in request.POST:
		motion_file = get_object_or_404(MotionFile, pk=request.POST['motion_file_id'])
		description = request.POST['description'].strip()
		start_time = float(request.POST['start_time'])
		duration = int(time.time() - start_time)
		annotation = Annotation(user=request.user, motion_file=motion_file, description=description, duration=duration)
		annotation.accept_language = request.META.get('HTTP_ACCEPT_LANGUAGE')
		annotation.ip_address = get_ip(request)
		if annotation.is_valid():
			# Update motion file and save annotation.
			motion_file.mean_perplexity = 0.  # reset mean perplexity until it is re-computed
			with transaction.atomic():
				motion_file.save()
				annotation.save()
			messages.success(request, random.choice(MOTIVATIONAL_MESSAGES))
			return redirect('dataset:index')
		
		# Annotation is invalid, prepare context.
		problem_url = '&#109;&#097;&#105;&#108;&#116;&#111;:&#109;&#097;&#116;&#116;&#104;&#105;&#097;&#115;&#046;&#112;&#108;&#097;&#112;&#112;&#101;&#114;&#116;&#064;&#115;&#116;&#117;&#100;&#101;&#110;&#116;&#046;&#107;&#105;&#116;&#046;&#101;&#100;&#117;?subject=Problem%20with%20motion%20{}'.format(motion_file.id)
		skip_url = '{}?skip={}'.format(reverse('dataset:index'), motion_file.id)
		messages.error(request, 'We think that your description of this motion is not a single, complete sentence in English. Please try again. You can also <a href="{}" class="alert-link">report a problem</a> or <a href="{}" class="alert-link">skip this motion</a>.'.format(problem_url, skip_url))
		context['motion_file'] = motion_file
		context['description'] = description
		context['invalid'] = True
		context['start_time'] = start_time
	else:
		# Get skip ID.
		try:
			skip_id = max(-1, int(request.GET['skip']))
		except:
			skip_id = -1

		# Mark as broken, if applicable.
		try:
			broken_id = int(request.GET['broken'])
			broken_motion_file = MotionFile.objects.get(id=broken_id)
			broken_motion_file.is_broken_reported = True
			broken_motion_file.save()
		except:
			pass

		# Get all annotations that haven't been annotated yet.
		q = MotionFile.objects.exclude(annotation__user=request.user)  # get all MotionFiles that haven't been annotated by the user
		q = q.annotate(annotation_count=Count('annotation__id'))  # annotate each motion file with the number of annotations
		q = q.filter(is_hidden=False, is_broken_reported=False, is_broken_confirmed=False, annotation_count=0)
		values = q.values('id')
		ids = [v['id'] for v in values if v['id'] != skip_id]

		if len(ids) > 0:
			# There are still un-annotated motions, select uniformly from them.
			selected_id = np.random.choice(ids)
		else:
			# All motions have been annotated, use perplexity-based sampling.
			q = MotionFile.objects.exclude(annotation__user=request.user)  # get all MotionFiles that haven't been annotated by the user
			q = q.filter(is_hidden=False, is_broken_reported=False, is_broken_confirmed=False)
			values = q.values('id', 'mean_perplexity')
			ids = [v['id'] for v in values if v['id'] != skip_id]
			perplexities = np.array([v['mean_perplexity'] for v in values if v['id'] != skip_id])
			assert len(ids) == len(perplexities)

			if len(ids) == 0:
				# Nothing more to annotate.
				return render(request, 'dataset/all_done.html', {})

			# Select randomly.
			probabilities = perplexities / np.sum(perplexities)
			assert np.allclose(np.sum(probabilities), 1.)
			selected_id = np.random.choice(ids, p=probabilities)
		assert selected_id != skip_id
		motion_file = MotionFile.objects.get(id=selected_id)

		motion_file.annotation_count = motion_file.annotation_set.count()
		context['overall_mean_perplexity'] = MotionFile.objects.all().aggregate(Avg('mean_perplexity'))['mean_perplexity__avg']
		context['motion_file'] = motion_file
		context['invalid'] = False
		context['start_time'] = time.time()

	# Fetch stats.
	users = User.objects.annotate(annotation_count=Count('annotation__id')).order_by('-annotation_count').all()
	all_user_ids = [user.id for user in users]
	all_annotation_counts = [user.annotation_count for user in users]
	ranked_user_idx = all_user_ids.index(request.user.id)
	user_count_annotations = all_annotation_counts[ranked_user_idx]
	total_count_motions = MotionFile.objects.filter(is_hidden=False).count()
	percentage_complete = float(user_count_annotations) / float(total_count_motions)
	lower_threshold, upper_threshold, name, klass = level_for_number_of_annotations(user_count_annotations)

	context['level_class'] = klass
	context['level_progress'] = int(round(float(user_count_annotations - lower_threshold) / float(upper_threshold - lower_threshold + 1) * 100.))
	context['level_name'] = name
	context['user_count_annotations'] = user_count_annotations
	context['total_count_motions'] = total_count_motions
	context['user_rank'] = ranked_user_idx + 1
	context['total_count_users'] = len(users)

	# Render result.
	context['motion_file_url'] = static('motions/' + context['motion_file'].filename)
	return render(request, 'dataset/annotate.html', context)


def stats(request):
	if not request.user.is_authenticated():
		return redirect('dataset:sign-in')

	# Fetch stats.
	users = User.objects.annotate(annotation_count=Count('annotation__id')).order_by('-annotation_count').all()
	max_annotation_count = users[0].annotation_count
	total_motions = MotionFile.objects.filter(is_hidden=False, is_broken_reported=False, is_broken_confirmed=False).count()
	total_annotations = Annotation.objects.filter(motion_file__is_hidden=False, motion_file__is_broken_reported=False, motion_file__is_broken_confirmed=False).count()
	total_users = len(users)
	distinct_annotations = Annotation.objects.filter(motion_file__is_hidden=False, motion_file__is_broken_reported=False, motion_file__is_broken_confirmed=False).values('motion_file_id').distinct().count()
	
	for idx, user in enumerate(users):
		percentage_complete = float(user.annotation_count) / float(total_motions)
		_, _, name, klass = level_for_number_of_annotations(user.annotation_count)
		user.level_class = klass
		user.level_name = name
		user.rank = idx + 1
		user.progress = float(user.annotation_count) / float(max_annotation_count) * 100.
		user.total_progress = int(round(percentage_complete * 100.))

	context = {
		'users': users,
		'total_motions': total_motions,
		'total_annotations': total_annotations,
		'total_users': total_users,
		'distinct_annotations': distinct_annotations,
		'percentage_complete': int(round(float(distinct_annotations) / float(total_motions) * 100.)),
		'annotations_per_motion': float(total_annotations) / float(total_motions),
	}
	return render(request, 'dataset/stats.html', context)


def logout(request):
	auth.logout(request)
	return redirect('dataset:index')

def register(request):
	if request.user.is_authenticated():
		return redirect('dataset:index')

	email = ''
	username = ''
	if 'email' in request.POST:
		username = request.POST['username']
		email = request.POST['email']
		password = request.POST['password']
		password_repeat = request.POST['password-repeat']

		# Validate.
		try:
			validate_email(email)
			is_valid_email = True
		except ValidationError:
			is_valid_email = False
		is_valid_username = len(username) > 0
		is_valid_password = (len(password) > 5)
		is_valid_repeat_password = (password == password_repeat)

		if not is_valid_username:
			messages.error(request, 'The username you entered appears to be invalid. Please try again.')
		elif not is_valid_email:
			messages.error(request, 'The email address you entered appears to be invalid. Please try again.')
		elif not is_valid_password:
			messages.error(request, 'Your password is too short. Please use a password that contains at least 6 characters.')
		elif not is_valid_repeat_password:
			messages.error(request, 'The passwords you entered do not match. Please try again.')
		else:
			try:
				user = User.objects.create_user(username=username,
										 		email=email,
										 		password=password)
				success = True
			except IntegrityError:
				success = False
				url = reverse('dataset:sign-in')
				message = 'Your username or email address was already used to register an account. Please <a href="{}" class="alert-link">sign in</a> or use a different email address.'.format(url)

src/dataset/templates/dataset/all_done.html
{% extends "dataset/base.html" %}

{% block content %}
<h1>All done!</h1>
<p>You have actually annotated every single motion there is to annotate. Congratulations, I guess...?</p>
{% endblock content %}

src/dataset/templates/dataset/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Motion Annotation Tool</title>

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link href="{% static "css/docnav.css" %}" rel="stylesheet">
    
    <script src="{% static "js/jquery-1.12.0.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/styles/solarized-light.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/highlight.min.js"></script>
    <style type="text/css">.hljs{ background: none; }</style>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Motion Annotation Tool</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="{% ifequal request.path '/' %}active{% endifequal %}"><a href="/">Annotate <span class="sr-only">(current)</span></a></li>
            <li class="{% ifequal request.path '/stats/' %}active{% endifequal %}"><a href="{% url 'dataset:stats' %}">Statistics</a></li>
          {% else %}
            <li class="{% ifequal request.path '/' %}active{% endifequal %}"><a href="/">Welcome <span class="sr-only">(current)</span></a></li>
          {% endif %}
            <li class="{% ifequal request.path '/dataset/' %}active{% endifequal %}"><a href="{% url 'dataset:dataset' %}">Dataset <span class="sr-only">(current)</span></a></li>
          </ul>
          {% if not request.user.is_authenticated %}
            <p class="navbar-text">by the <a href="https://h2t.anthropomatik.kit.edu">H²T lab</a> at <a href="https://kit.edu">KIT</a></p>
          {% endif %}
          
          {% if request.user.is_authenticated %}
          <p class="navbar-text navbar-right" style="padding-right:15px;">Signed in as {{ request.user.username }}. <a href="{% url 'dataset:logout' %}">Sign out</a></p>
          {% else %}
          <form method="post" action="{% url 'dataset:sign-in' %}" class="navbar-form navbar-right" role="sign-in">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" placeholder="Username or Email" class="form-control" name="username" autocomplete="off" autocapitalize="off" autocorrect="off">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control" name="password">
            </div>
            <button type="submit" value="login" class="btn btn-success">Sign in</button>
            <button type="button" class="btn btn-link" onclick="location.href='{% url 'dataset:register' %}';">Sign up</button>
            <input type="hidden" name="next" value="/">
          </form>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}{% endblock content %}

      <footer class="footer text-center">
        <p><small>&copy; 2016 <a href="http://matthiasplappert.com">Matthias Plappert</a>, Adenauerring 2 (Gebäude 50.20), 76131 Karlsruhe, Germany. <a href="&#109;&#097;&#105;&#108;&#116;&#111;:&#109;&#097;&#116;&#116;&#104;&#105;&#097;&#115;&#046;&#112;&#108;&#097;&#112;&#112;&#101;&#114;&#116;&#064;&#115;&#116;&#117;&#100;&#101;&#110;&#116;&#046;&#107;&#105;&#116;&#046;&#101;&#100;&#117;">&#109;&#097;&#116;&#116;&#104;&#105;&#097;&#115;&#046;&#112;&#108;&#097;&#112;&#112;&#101;&#114;&#116;&#064;&#115;&#116;&#117;&#100;&#101;&#110;&#116;&#046;&#107;&#105;&#116;&#046;&#101;&#100;&#117;</a>.<br>Provided by the <a href="https://h2t.anthropomatik.kit.edu">H²T lab</a> at the <a href="https://kit.edu">Karlsruhe Institute of Technology (KIT)</a></small></p>
      </footer>
    </div>
  
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-81199330-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

src/dataset/templates/dataset/messages.html
{% for message in messages %}
  <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">{{ message | safe }}</div>
{% endfor %}

src/dataset/templates/dataset/register.html
{% extends "dataset/base.html" %}

{% block content %}
<h1>Account Registration</h1>

{% if messages %}
  {% include "dataset/messages.html" %}
{% else %}
  <div class="alert alert-info" role="alert">If you are a member of the <a href="https://h2t.anthropomatik.kit.edu/index.php" class="alert-link">H²T team</a>, you do not need to create an account. Simply use your Redmine username and password to <a href="{% url 'dataset:sign-in' %}" class="alert-link">sign in</a>.</div>
{% endif %}

<form action="{% url 'dataset:register' %}" method="post" class="form-horizontal">
  {% csrf_token %}
  <div class="form-group">
    <label for="username" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="username" name="username" placeholder="Username" value="{{ username }}" autocomplete="off" autocapitalize="off" autocorrect="off">
      <p class="help-block">The username will be visible publicly. Please make sure that you only use your real name if you are comfortable sharing it with others.</p>
    </div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Email address</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="{{ email }}">
    </div>
  </div>
  <div class="form-group">
    <label for="password" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="password" name="password" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <label for="password-repeat" class="col-sm-2 control-label">Repeat password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="password-repeat" name="password-repeat" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>
{% endblock content %}

src/dataset/templates/dataset/sign-in.html
{% extends "dataset/base.html" %}

{% block content %}
<h1>Sign In</h1>

{% if form.errors %}
  <div class="alert alert-danger" role="alert">No matching account found. Please try again.</div>
{% else %}
  <div class="alert alert-info" role="alert">If you are a member of the <a href="https://h2t.anthropomatik.kit.edu/index.php" class="alert-link">H²T team</a>, you do not need to create an account. Simply use your Redmine username and password to sign in.</div>
{% endif %}

<form method="post" action="{% url 'dataset:sign-in' %}" class="form-horizontal">
  {% csrf_token %}
  <div class="form-group">
    <label for="username" class="col-sm-2 control-label">Username or Email</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="username" name="{{ form.username.name }}" placeholder="Username or Email" autocomplete="off" autocapitalize="off" autocorrect="off">
    </div>
  </div>
  <div class="form-group">
    <label for="password" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="password" name="{{ form.password.name }}" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" value="login" class="btn btn-default">Submit</button>
      <p class="help-block">If you don't have an account yet, you can <a href="{% url 'dataset:register' %}">create one</a>.</p>
    </div>
  </div>
  <input type="hidden" name="next" value="/" />
</form>
{% endblock content %}

src/dataset/templates/dataset/welcome.html
{% extends "dataset/base.html" %}
{% load staticfiles %}

{% block content %}
<script src="{% static "js/three.min.js" %}"></script>
<script src="{% static "js/controls.min.js" %}"></script>
<script src="{% static "js/viewer.min.js" %}"></script>
<script>$(document).ready(initViewer('{% static "motions/0059ac190ecdcf04e0700e9c9827bf3e917bbddd.json" %}', true, new THREE.Vector3(20, 0, 15), new THREE.Vector3(0, 0, 10)));</script>

<h1>Welcome</h1>
<p class="lead">The goal of this website is to annotate human whole-body motion with natural language. This dataset will hopefully enable us to learn a mapping between motion and language. Such a mapping would be pretty useful since it would allow us to generate motion from natural language, for example in a humanoid robot. However, we need your help to collect it!</p>

<h2>The Dataset</h2>
<p>If you're looking for the <em>KIT Motion-Language Dataset</em>, which contains the motion data and their annotations that have been collected through this website, look no further. You can freely <a href="{% url 'dataset:dataset' %}">download the dataset</a>. The download page also contains additional information and code example to help you get started.</p>

<h2>Getting Started</h2>
<div class="row border-between">
  <div class="col-md-4">
  	<div class="number">1</div>
  	<p>You'll first need an account. But don't worry, creating one is very easy and completely hassle-free. Simply <a href="{% url 'dataset:register' %}">sign up</a>.</p>
  	<p>If you are a member of the <a href="https://h2t.anthropomatik.kit.edu/index.php" class="alert-link">H²T team</a>, you don't even need to do that. Just <a href="{% url 'dataset:sign-in' %}">sign in</a> with your Redmine account!<p>
  </div>
  <div class="col-md-4">
    <div class="number">2</div>
    <p>As soon as you are signed in, we'll start showing you human whole-body motions like the one below.<p>
    <div id="example-motion">
      {% include "dataset/viewer.html" %}
    </div>
    <p>We've made sure that you can inspect the motion as necessary. You can use the <em>left mouse button</em> to rotate the camera.
    Use the <em>mouse wheel</em> to zoom in and out. You can familiarize yourself with the controls in the example above. Give it a try now, it's fun!<p>
  </div>
  <div class="col-md-4">
    <div class="number">3</div>
    <p>The annotation process is really simple: After we've shown you a motion (like the one on the left), we ask you tell us in a single sentence and in plain English what you see. That's it!</p>
    <p>To give you a concrete example, a possible annotation for the motion that you're watching right now could be:</p>
    <blockquote>
  		<p>&ldquo;A person performs a single squat.&rdquo;</p>
	</blockquote>
	<p>To make sure that the data we collect is consistent, we ensure that only a single sentence is entered and that the majority of words are spelled correctly.</p>
  </div>
</div>

<h2>Additional Information</h2>
<p>If you are interested, we are more than happy to give you more details of the nature and the purpose of this dataset. All motions were recorded at the <a href="https://h2t.anthropomatik.kit.edu/index.php">High Performance Humanoid Technologies (H²T)</a>, which is part of the Faculty of Informatics at the <a href="https://kit.edu">Karlsruhe Insitute of Technology</a>. All recorded motion is freely available through the <a href="https://motion-database.humanoids.kit.edu/">KIT Whole-Body Human Motion Database</a>. While these motions are annotated with simple tags (e.g. walk, run, ...), they lack more comprehensive annotations in the form of natural language.</p>

<p>This website was created during a student research program called <a href="http://formal.iti.kit.edu/projektgruppe">&ldquo;Praxis der Forschung&rdquo;</a>. During this program, several students can work on a project for two semesters and hopefully arrive at interesting results. In our case, we are interested in a better understanding of human motion and natural language. More precisely, we are interested in learning a bidirectional mapping that would allow us to essentially translate between motion and language. Such a system would be extremely useful in various scenarios. Imagine, for example, a humanoid robot that would be able to perform a motion in response to a command uttered in natural language.</p>

<p>To work on this project, we need a large dataset. This is why we created this website to help us annotate existing motions with natural language. We can then use this dataset to train machines to understand the connection between motion and language using machine learning techniques. We also plan to make this dataset freely available to everybody, so that everybody can experiment with it.</p>

{% endblock content %}